development:
  adapter: postgresql
  encoding: unicode
  database: air_quality_microservice
  pool: 2
  username: Joseph Mecha
  password: arapaho
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>